file=open("OFL.txt",'w')
write=input("enter the text to be written in to the file:\n")
file.write(write)
print("text written in to the file sucessfully")
file.close()
file=open("OFL.txt",'a')
app=input("enter the appendage text:\n")
ap=file.writelines( "\n"+ app)
print("appendages added sucessfully") 
file.close()  
file=open("OFL.txt",'r')
print("The final output reads like this:\n",file.read())     